[package]
name = "ots-aggregator"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo.casatta@gmail.com>"]

[dependencies]
hyper = "0.11"
futures = "0.1.14"
tokio = "0.1"
tokio-core = "0.1"
rand = "0.4.2"
rust-crypto = "~0.2"
data-encoding = "2.1.1"
